modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="girlfriend" 
version="${file.jarVersion}"
displayName="Girlfriend Mod"
logoFile="" 
credits="Thanks to Rin and Brooke for the skins"
description='''
Mod by Squakas.
'''

[[dependencies.girlfriend]]
    modId="forge"
    mandatory=true 
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.girlfriend]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
